### ISSUE TITLE
Problem during require (ChainedBlock)

### ISSUE THREAD

**Issue by dohzya** [svenfuchs/ripper2ruby#1]
I think there is a problem of loading order...

<pre>
svenfuchs-ripper2ruby-0.0.2/lib/ruby/if.rb:4:in `<module:Ruby>': uninitialized constant Ruby::ChainedBlock (NameError)
</pre>

**Comment by dohzya** [comment]
oops, bad copy-n-paste

<pre>
svenfuchs-ripper2ruby-0.0.2/lib/ruby/if.rb:4:in 'require':LoadError: uninitialized constant Ruby::ChainedBlock (NameError)
</pre>

**Comment by janfri** [comment]
I have had an error message similar to yours, it is indeed a problem with the loading order. I have added sorting of the filenames of the require array and it seems to work. See my clone http://github.com/janfri/ripper2ruby/tree/master . Pull request already send to svenfuchs.

**Comment by svenfuchs** [comment]
applied, thanks a lot, guys :)
